# Generated by Django 4.1.2 on 2022-10-08 16:43

import Admission.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient_Visit', '0001_initial'),
        ('Patient_Files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ward', '0001_initial'),
        ('Visit_Clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Admission_Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admission_Description', models.TextField(blank=True, null=True, verbose_name='Admission_Description')),
                ('ins_user_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Start_Admission_Date', models.DateTimeField(blank=True, null=True)),
                ('End_Admission_Date', models.DateTimeField(blank=True, null=True)),
                ('Discharge_status', models.BooleanField(default=False)),
                ('Discharge_Date', models.DateTimeField(blank=True, null=True)),
                ('Visit_Case_is_Closed', models.BooleanField(default=False)),
                ('Discharge_OF_Section_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('Admission_Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Section_%(class)s_objects', to='Ward.admission_section')),
                ('Visit_Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient_Visit.pateint_visit', unique=True)),
                ('Visit_Clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visit_Clinic.pateint_visit_clinic_case', unique=True)),
                ('ins_user_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patiant_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_%(class)s_objects', to='Patient_Files.patiant_file_no')),
            ],
            options={
                'db_table': 'Patient_Admission_Case',
                'unique_together': {('Visit_Case', 'Visit_Clinic')},
            },
        ),
        migrations.CreateModel(
            name='Patient_Admission_Case_Visit_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Admission_Of_Section_Date', models.DateTimeField(blank=True, null=True)),
                ('End_Admission_Of_Section_Date', models.DateTimeField(blank=True, null=True)),
                ('Accept_OF_Section_Status', models.BooleanField(default=False)),
                ('Accept_OF_Section_Date', models.DateTimeField(blank=True, null=True)),
                ('is_Transfer', models.BooleanField(default=False)),
                ('Visit_Status', models.BooleanField(default=False)),
                ('Visit_Transfer', models.BooleanField(default=False)),
                ('Visit_Transfer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('Nurse_Confirmation_Transfer', models.BooleanField(default=False)),
                ('Asing_To_Bed_Status', models.BooleanField(default=False)),
                ('Assgin_To_Bed_Date', models.DateTimeField(blank=True, null=True)),
                ('is_Discharge', models.BooleanField(default=False)),
                ('Discharge_OF_Section_Status', models.BooleanField(default=False)),
                ('Discharge_OF_Section_Date', models.DateTimeField(blank=True, null=True)),
                ('Discharge_Description', models.TextField(blank=True, null=True, verbose_name='Transfer_Description2')),
                ('Visit_is_Closed', models.BooleanField(default=False)),
                ('Reason_for_Visit_closed', models.CharField(blank=True, max_length=200, null=True)),
                ('Admission_Case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admission_Case_id2', to='Admission.patient_admission_case')),
                ('BED', models.ForeignKey(blank=True, limit_choices_to={'in_Use': False, 'is_activate': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Patient_Admission_Case_Visit_Bed_Number2', to='Ward.admission_room_bed')),
                ('Discharge_By_User_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Discharge_By_User_Code2', to=settings.AUTH_USER_MODEL)),
                ('Patient_No', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pateiant_No_Case_Visit_Section2', to='Patient_Files.patiant_file_no')),
                ('ROOM_NO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ward.admission_room')),
                ('Section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Section_Case2', to='Ward.admission_section')),
            ],
            options={
                'db_table': 'Patient_Admission_Case_Visit_Section',
            },
        ),
        migrations.CreateModel(
            name='Transfer_Tybe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tybe_Name', models.CharField(max_length=21, unique=True)),
            ],
            options={
                'db_table': 'Transfer_Tybe',
            },
        ),
        migrations.CreateModel(
            name='Transfer_Patient_To_ِِanother_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transfer_Description', models.TextField(blank=True, null=True, verbose_name='Transfer_Description')),
                ('Transfer_By_Doctor_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Approve_by_Nurse_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Transfer_completed_Status', models.BooleanField(default=False)),
                ('Approve_by_Nurse_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Approve_by_Nurse_id2', to=settings.AUTH_USER_MODEL)),
                ('Transfer_By_Doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transfer_By_Doctor_id2', to=settings.AUTH_USER_MODEL)),
                ('Transfer_From_Section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transfer_From_Section2', to='Ward.admission_section')),
                ('Transfer_To_Section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transfer_TO_Section2', to='Ward.admission_section')),
                ('Transfer_Tybe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admission.transfer_tybe')),
                ('Visit_Section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visit_Section_id2', to='Admission.patient_admission_case_visit_section')),
            ],
            options={
                'db_table': 'Transfer_Patient_To_ِِanother_Section',
            },
        ),
        migrations.CreateModel(
            name='Patient_Admission_Vital_Signs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_user_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('Temp', models.FloatField(null=True)),
                ('Blood_pressure', models.CharField(blank=True, max_length=21, null=True)),
                ('spo2', models.CharField(blank=True, max_length=21, null=True, verbose_name='Spo2 ( % )')),
                ('Resp_rate', models.IntegerField()),
                ('clum_1', models.CharField(blank=True, max_length=21, null=True)),
                ('clum_2', models.CharField(blank=True, max_length=21, null=True)),
                ('clum_3', models.CharField(blank=True, max_length=21, null=True)),
                ('Admission_visit_Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admission_Visit_id_%(class)s_objects', to='Admission.patient_admission_case_visit_section')),
                ('ins_user_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patiant_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admission_Visit_Patient_%(class)s_objects', to='Patient_Files.patiant_file_no')),
            ],
            options={
                'db_table': 'Patient_Admission_Vital_Signs',
            },
        ),
        migrations.CreateModel(
            name='Patient_Admission_Order_Nurse_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_user_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('Titel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titel :')),
                ('Nurse_Note', models.TextField(verbose_name='Details :')),
                ('Note_Files', models.ImageField(blank=True, max_length=255, null=True, upload_to=Admission.models.Patient_Admission_Order_Images, verbose_name='Upload Files :')),
                ('Admission_visit_Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admission_Visit_id_%(class)s_objects', to='Admission.patient_admission_case_visit_section')),
                ('ins_user_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patiant_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admission_Visit_Patient_%(class)s_objects', to='Patient_Files.patiant_file_no')),
            ],
            options={
                'db_table': 'Patient_Admission_Order_Nurse_Note',
            },
        ),
        migrations.CreateModel(
            name='Patient_Admission_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_user_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('Dr_Order', models.CharField(blank=True, max_length=100, null=True)),
                ('Nurse_Note', models.TextField(verbose_name='Nurse_Note')),
                ('Nurse_Result_Time', models.DateTimeField(blank=True, null=True)),
                ('order_status', models.BooleanField(default=False)),
                ('Visit_Files', models.ImageField(blank=True, max_length=255, null=True, upload_to=Admission.models.Patient_Admission_Order_Images)),
                ('Admission_visit_Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admission_Visit_id_%(class)s_objects', to='Admission.patient_admission_case_visit_section')),
                ('ins_user_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patiant_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admission_Visit_Patient_%(class)s_objects', to='Patient_Files.patiant_file_no')),
            ],
            options={
                'db_table': 'Patient_Admission_Order',
            },
        ),
        migrations.CreateModel(
            name='Patient_Admission_Doctor_Examination_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_user_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('History', models.TextField(blank=True, null=True, verbose_name='History & Physical')),
                ('Diagnosis', models.TextField(blank=True, null=True, verbose_name='Diagnosis')),
                ('Examination', models.TextField(blank=True, null=True, verbose_name='Examination')),
                ('Doctor_Note', models.TextField(blank=True, null=True, verbose_name='Doctor Note')),
                ('Admission_visit_Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admission_Visit_id_%(class)s_objects', to='Admission.patient_admission_case_visit_section')),
                ('ins_user_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patiant_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admission_Visit_Patient_%(class)s_objects', to='Patient_Files.patiant_file_no')),
            ],
            options={
                'db_table': 'Patient_Admission_Doctor_Examination_History',
            },
        ),
        migrations.CreateModel(
            name='Admission_Visit_Xray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_user_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('Status_Reception_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('xray_status', models.CharField(choices=[('Waiting Reception', 'Waiting Reception'), ('Waiting Report', 'Waiting Report'), ('Finish', 'Finish')], default='Waiting Reception', max_length=20)),
                ('Admission_visit_Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admission_Visit_id_%(class)s_objects', to='Admission.patient_admission_case_visit_section')),
                ('Visit_History', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admission.patient_admission_doctor_examination_history')),
                ('Xray_Site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Xray_Site_Visits', to='Visit_Clinic.xray_site')),
                ('Xray_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Xray_Type_Visits', to='Visit_Clinic.xray_type')),
                ('ins_user_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patiant_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Admission_Visit_Patient_%(class)s_objects', to='Patient_Files.patiant_file_no')),
            ],
            options={
                'db_table': 'Patiant_admission_Xray',
            },
        ),
    ]
