# Generated by Django 4.1.2 on 2022-10-09 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Visit_Clinic', '0001_initial'),
        ('Patient_Visit', '0003_alter_pateint_visit_visit_date'),
        ('Admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_admission_case',
            name='Visit_Case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient_Visit.pateint_visit'),
        ),
        migrations.AlterField(
            model_name='patient_admission_case',
            name='Visit_Clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visit_Clinic.pateint_visit_clinic_case'),
        ),
    ]
