# Generated by Django 4.1 on 2022-10-17 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ward', '0001_initial'),
        ('Admission', '0002_alter_patient_admission_case_visit_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_admission_case',
            name='Admission_Section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_Visit_Section_Ward', to='Ward.admission_section'),
        ),
    ]
