# Generated by Django 4.1.2 on 2022-10-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admission', '0003_alter_patient_admission_case_admission_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient_admission_order',
            options={'ordering': ('-id',)},
        ),
    ]
