# Generated by Django 4.1.2 on 2022-10-08 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_Name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hospital Name')),
                ('Cloud_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cloud Site Primary')),
                ('Cloud_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cloud Site Scandry')),
            ],
            options={
                'verbose_name_plural': 'Hospital list',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEPARTEMNT', models.CharField(blank=True, max_length=50)),
                ('Active', models.BooleanField(default=False)),
                ('hospital_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.hospital_list')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
