# Generated by Django 4.1.2 on 2022-10-24 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_Files', '0001_initial'),
        ('accounts', '0002_role_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEPARTEMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEPARTEMENT_Name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Hospital_DEPARTEMENTs',
            },
        ),
        migrations.CreateModel(
            name='Employee_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Type', models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Nurse', 'Xray'), ('Radiology', 'Radiology'), ('Medecal Report', 'Medecal Report'), ('Medecal Record', 'Medecal Record'), ('Reception', 'Reception')], max_length=200, null=True, verbose_name='Employee_Type')),
            ],
            options={
                'db_table': 'Employee_Type',
            },
        ),
        migrations.CreateModel(
            name='job_catogery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_catogery', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'job_catogery',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='DEPARTEMNT',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hospital_Name',
        ),
        migrations.AddField(
            model_name='profile',
            name='ID_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Nationlity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NationalityIS', to='Patient_Files.nationality'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='DEPARTEMNTS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DEPARTEMENTIS', to='accounts.departement'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Employee_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Employee_Types', to='accounts.employee_type'),
        ),
        migrations.AddField(
            model_name='profile',
            name='jobcatogery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcatogery', to='accounts.job_catogery'),
        ),
    ]
