# Generated by Django 4.1.2 on 2022-10-08 16:43

import Visit_Clinic.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patient_Visit', '0001_initial'),
        ('Patient_Files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pateint_Visit_Clinic_Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visit_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Visit_Date', models.DateTimeField(auto_now_add=True)),
                ('Vital_Signs_Status', models.BooleanField(default=False)),
                ('Visit_Opened_status', models.BooleanField(default=False)),
                ('Opened_Date', models.DateTimeField(blank=True, null=True)),
                ('is_Close', models.BooleanField(default=False)),
                ('Closed_Date', models.DateTimeField(blank=True, null=True)),
                ('Close_Details', models.CharField(blank=True, max_length=100, null=True)),
                ('is_Transfer', models.BooleanField(default=False)),
                ('Transfer_Date', models.DateTimeField(blank=True, null=True)),
                ('Transfer_Details', models.CharField(blank=True, max_length=100, null=True)),
                ('Clinic_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Clinic_Name_%(class)s_objects', to='App_Home.clinic_list')),
                ('Close_By_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Close_By_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('Open_By_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Opened_By_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('Patiant_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient_Files.patiant_file_no')),
                ('Transfer_By_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transfer_By_%(class)s_objects', to=settings.AUTH_USER_MODEL)),
                ('Visit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient_Visit.pateint_visit')),
            ],
            options={
                'db_table': 'Pateint_Visit_Clinic_Case',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Patiant_Visit_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_user_date', models.DateTimeField(auto_now_add=True)),
                ('History', models.TextField(blank=True, null=True, verbose_name='History & Physical')),
                ('Diagnosis', models.TextField(blank=True, null=True, verbose_name='Diagnosis')),
                ('Examination', models.TextField(blank=True, null=True, verbose_name='Examination')),
                ('Doctor_Note', models.TextField(blank=True, null=True, verbose_name='Doctor Note')),
                ('ins_user_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patiant_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_%(class)s_objects', to='Patient_Files.patiant_file_no')),
                ('visit_Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visit_id_%(class)s_objects', to='Visit_Clinic.pateint_visit_clinic_case')),
            ],
            options={
                'db_table': 'Patiant_Visit_History',
            },
        ),
        migrations.CreateModel(
            name='Patiant_Visit_Xray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_user_date', models.DateTimeField(auto_now_add=True)),
                ('Status_Reception_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('xray_status', models.CharField(choices=[('Waiting Reception', 'Waiting Reception'), ('Waiting Report', 'Waiting Report'), ('Finish', 'Finish')], default='Waiting Reception', max_length=20)),
                ('Visit_History', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visit_Clinic.patiant_visit_history')),
            ],
            options={
                'db_table': 'Patiant_Visit_Xray',
            },
        ),
        migrations.CreateModel(
            name='Xray_Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Xray_Site', models.CharField(blank=True, max_length=21, null=True)),
            ],
            options={
                'db_table': 'Xray_Site',
            },
        ),
        migrations.CreateModel(
            name='Xray_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Xray_type', models.CharField(blank=True, max_length=21, null=True)),
            ],
            options={
                'db_table': 'Xray_type',
            },
        ),
        migrations.CreateModel(
            name='Patiant_Visit_Xray_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report_details', models.TextField(blank=True, null=True, verbose_name='Report_details')),
                ('Report_time', models.DateTimeField(blank=True, null=True)),
                ('is_visit', models.BooleanField(default=False)),
                ('visit_time', models.DateTimeField(blank=True, null=True)),
                ('Order_xray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_xray', to='Visit_Clinic.patiant_visit_xray')),
            ],
            options={
                'db_table': 'Patiant_Visit_Xray_Report',
            },
        ),
        migrations.AddField(
            model_name='patiant_visit_xray',
            name='Xray_Site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Xray_Site_Visit', to='Visit_Clinic.xray_site'),
        ),
        migrations.AddField(
            model_name='patiant_visit_xray',
            name='Xray_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Xray_Type_Visit', to='Visit_Clinic.xray_type'),
        ),
        migrations.AddField(
            model_name='patiant_visit_xray',
            name='ins_user_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patiant_visit_xray',
            name='patiant_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_%(class)s_objects', to='Patient_Files.patiant_file_no'),
        ),
        migrations.AddField(
            model_name='patiant_visit_xray',
            name='visit_Case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visit_id_%(class)s_objects', to='Visit_Clinic.pateint_visit_clinic_case'),
        ),
        migrations.CreateModel(
            name='Patiant_Visit_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_user_date', models.DateTimeField(auto_now_add=True)),
                ('Dr_Order', models.CharField(blank=True, max_length=100, null=True)),
                ('Nurse_Note', models.TextField(verbose_name='Nurse_Note')),
                ('Nurse_Result_Time', models.DateTimeField(blank=True, null=True)),
                ('order_status', models.BooleanField(default=False)),
                ('Visit_Files', models.ImageField(blank=True, null=True, upload_to=Visit_Clinic.models.Patient_Visit_Order_Images)),
                ('ins_user_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patiant_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_%(class)s_objects', to='Patient_Files.patiant_file_no')),
                ('visit_Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visit_id_%(class)s_objects', to='Visit_Clinic.pateint_visit_clinic_case')),
            ],
            options={
                'db_table': 'Patiant_Visit_Order',
            },
        ),
    ]
