# Generated by Django 4.1 on 2022-10-16 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_Visit', '0003_alter_pateint_visit_visit_date'),
        ('Visit_Clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pateint_visit_clinic_case',
            name='Visit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visits', to='Patient_Visit.pateint_visit'),
        ),
    ]
