# Generated by Django 4.1.2 on 2022-10-09 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_Visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pateint_visit',
            name='Visit_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
