# Generated by Django 4.1.2 on 2022-10-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_Visit', '0002_alter_pateint_visit_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pateint_visit',
            name='Visit_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
