# Generated by Django 4.1.2 on 2022-10-08 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clinic_Name', models.CharField(max_length=21, null=True)),
                ('Clinic_Tybe', models.CharField(choices=[('OPD', 'OPD'), ('ER', 'ER')], max_length=190)),
                ('Clinic_status', models.BooleanField(default=False)),
                ('User_Access', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Clinic_List',
            },
        ),
    ]
