# Generated by Django 4.1.2 on 2022-10-08 16:43

import Nurse.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Visit_Clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patient_Files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit_Vital_Signs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_user_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Body_weight', models.FloatField(null=True)),
                ('Height', models.FloatField(null=True)),
                ('Temp', models.FloatField(null=True)),
                ('Blood_pressure', models.CharField(blank=True, max_length=21, null=True)),
                ('spo2', models.CharField(blank=True, max_length=21, null=True, verbose_name='Spo2 ( % )')),
                ('Resp_rate', models.IntegerField()),
                ('Vital_Status', models.BooleanField(default=False)),
                ('ins_user_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patiant_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_%(class)s_objects', to='Patient_Files.patiant_file_no')),
                ('visit_Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visit_id_%(class)s_objects', to='Visit_Clinic.pateint_visit_clinic_case')),
            ],
            options={
                'db_table': 'Visit_Vital_Signs',
            },
        ),
        migrations.CreateModel(
            name='Patiant_Visit_Nurse_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_user_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Nurse_Note', models.TextField(verbose_name='Patiant_Nurse_Note')),
                ('Note_Files', models.ImageField(blank=True, max_length=255, null=True, upload_to=Nurse.models.path_and_rename)),
                ('ins_user_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patiant_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_%(class)s_objects', to='Patient_Files.patiant_file_no')),
                ('visit_Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visit_id_%(class)s_objects', to='Visit_Clinic.pateint_visit_clinic_case')),
            ],
            options={
                'db_table': 'Patiant_Visit_Nurse_Note',
            },
        ),
    ]
